### ISSUE TITLE
The settings is not clear

### ISSUE THREAD

**Issue by lianghu** [pl-ca/ClangAutoComplete#11]
There is no settings under the Preferences->Package Settings for this plugin.
Where to put the user settings?   in the top setting file  Preferences->Settings-User?

The include_dirs is not unique for single plugin, and it's not proper to set it in top setting file.

**Comment by pl-ca** [comment]
Sorry, it is indeed missing from the _Preferences_ menu. I will see how to add it there.
In the meantime, you can directly open the file located at `Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.sublime-settings` to edit the settings to your needs.

**Comment by JohannesMP** [comment]
It would be best if `ClangAutoComplete.sublime-settings` was located in `Packages\User`. That seems to be the default location for most Packages.

**Comment by pl-ca** [comment]
You are right, it would be better. I've been quite busy the last few weeks and I did not have time to do the change and test it. I'll see if I can do that soon.

**Comment by pl-ca** [comment]
I finally added a menu entry to access the settings in Preferences/Package Settings/ClangAutoComplete/settings
