### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by cidadao** [pl-ca/ClangAutoComplete#12]
I just installed ClangAutoComplete through Package Control and I'm editing a C file but nothing (i.e. auto-completion) happens.
I don't get any Clang output on Console.

I'm using Windows and ST3. What should be going wrong?

**Comment by pl-ca** [comment]
Hi, I'm sorry but this does not appear to be my plugin (ClangAutoComplete), but another similar one (Clan-Complete) :)

I suggest posting that on their page, or trying mine instead!
