### ISSUE TITLE
Not working, no error in console

### ISSUE THREAD

**Issue by niosus** [pl-ca/ClangAutoComplete#19]
Hello! Thanks for the efforts to bring the proper autocompletion to Sublime! 
However, after installing and configuring the package, I do not seem to get any response from the code. I have configured the symbols that trigger autocompletion as you suggested, but when I type some code and click `.` there is no auto-completion window.

There is also no error in the console. I am sure that `clang++` is in the path. Do you have any idea what can be going on here? Where should I dig?

**Comment by pl-ca** [comment]
Hi, I am away so I can't be of much help for the next week, but I can suggest you to look at the includes settings.

For more details, you can open the clangautocomplete.py file and add "print clang_cmd" after the line where it is initialized. Then open the console and attempt to trigger auto completion with "." 

Copy paste the output command from the console into a terminal window and see what error it returns. Typically it will be regarding a missing header file from the settings.

**Comment by niosus** [comment]
Thanks for a fast reply and for the tip. Will do that!

**Comment by nlappas** [comment]
Same problem here. The "." does not seem to trigger anything. The console does not print anything even after adding the print clang_cmd line.

**Comment by pl-ca** [comment]
Did you make sure that sublime settings for auto-completion are working? If no suggestion window pops up it means that the plug-in is not even triggered.

To set them I click on `Preferences -> Settings - More -> Syntax Specific - User` and I find the following:

```
{
        "auto_complete": true,
        "auto_complete_selector": "source - comment",
        "auto_complete_triggers":
        [
                {
                        "characters": "."
                },
                {
                        "characters": ">"
                },
        ],
        "extensions":
        [
                "c",
                "h"
        ]
}
```

niosus, could you make it work or you are still having the same issue?

**Comment by niosus** [comment]
Thanks for the hint, @pl-ca  but I did that. It is definitely not the sublime completion triggers. I have now switched to YouCompleteMe and it works with the same settings for the completion triggers. Unfortunately I did not have time to investigate into the issue more though. I will probably be able to do it this week or around the weekend.

**Comment by pl-ca** [comment]
Alright, don't worry about investigating that issue if you found an alternative that works for you. I was not aware of that plugin, but it seems pretty nice!

**Comment by niosus** [comment]
@pl-ca nah, that plugin is also quite a hassle to use. So I decided to have a look at what is happening. I have added the print statement as you suggested: `print(clang_cmd)` as line 113 in `ClangAutoComplete.py`. 

I get the command that looks like this: `clang++-3.6 -cc1 -x c++ -fsyntax-only -code-completion-at /tmp/auto_complete_tmp:31:5 /tmp/auto_complete_tmp -I . -I /usr/lib/clang/3.6/include -I /usr/include -I /usr/local/include -I ./src

I originally had a couple of issues when just running it from the command line:
- `fatal error: 'sys/cdefs.h' file not found`
  + solved by `sudo apt-get install libc6-dev-i386`
- `fatal error: 'stddef.h' file not found`
  + solved by adding a new include path in the plugin settings to `/usr/lib/clang/3.6/include`

I am now struggling with smth like `fatal error: 'vector' file not found` and my search led me to http://clang.llvm.org/docs/FAQ.html where they state that one should not use the `-cc1` flag with clang.

Do you have an opinion on this?

**Comment by pl-ca** [comment]
Yes actually I've had trouble getting clang to find all standard headers and I though it was just me.
Here are what I had to include to make it work on my system. Are you able to find similar paths on yours? All first 3 lines were important to make it work for me. Let me know if this solves your problem (possibly paths could be a bit different). If it does i'll update the readme to include that.

```C
	"include_dirs" : [
					  "/usr/include/c++/4.4.7/",  /* Where you find iostream, vector, etc. */
					  "/usr/lib/clang/3.4.2/include",       /* stdbool, etc */
					  "/usr/include/c++/4.4.4/x86_64-redhat-linux/",  /* bits folder */
					  "/usr/include",
```

If you can't find the equivalent path try to search your system to find those key files and add the paths, i.e.
```bash
sudo find / -name "iostream"
sudo find / -name "stdbool.h"
sudo find / -name "c++config.h"
```

**Comment by niosus** [comment]
@pl-ca yep, that was exactly what I have done for me too. 
These are relevant lines from my `"include_dirs"`:

```
"include_dirs" : [
					"/usr/lib/clang/3.6/include",
					"/usr/include/c++/4.8",
					"/usr/include/x86_64-linux-gnu/c++/4.8",
					"/usr/include",
					...
					  ],
```

**Comment by pl-ca** [comment]
Just to confirm, is it working now, or you are still having issues even with those settings?

**Comment by niosus** [comment]
@pl-ca this is working. So I guess adding it to the readme is a nice idea after all.

However, what about adding some print statement that would tell a user that clang has produced garbage and that it is probably the include folders?

**Comment by pl-ca** [comment]
Alright thanks @niosus ! Your suggestion is wise.

I'll update the readme, close this issue, and open another one to track this feature.

**Comment by niosus** [comment]
:+1:
