### ISSUE TITLE
Provide better feedback to user as to what is not working whenever something fails

### ISSUE THREAD

**Issue by pl-ca** [pl-ca/ClangAutoComplete#20]
There is currently no mechanism by which the user can find what went wrong besides asking for help on github. There could be better debugging information, making use of the console or maybe output panel.

**Comment by hypernewbie** [comment]
I concur. I don't feel this plugin is well designed at all.

**Comment by pl-ca** [comment]
There is not much of a design to speak of, it is a (too) simple wrapper around clang binary. Having better tools around it would be desirable but I haven't been able to find the time in the recent weeks to do that. 

If you have something you need help with you can raise an issue here, or I can suggest you to take a look at [EasyClangComplete](https://github.com/niosus/EasyClangComplete) which is being maintained by @niosus more actively than this plug-in.

**Comment by pl-ca** [comment]
As of release 2.2.0, I included a `debug` flag in the settings that can be used to gather precise information as to why the completion failed.
