### ISSUE TITLE
 fatal error: `sys/cdefs.h` file not found

### ISSUE THREAD

**Issue by niosus** [pl-ca/ClangAutoComplete#22]
The full behavior looks like this: I run the plugin, try to autocomplete, it produces garbage, which is not shown in the sublime console. I copy the command to the terminal and runnning it gives me this error.

This happens to me on every x64 system I run the plugin on. I guess some hints about it can be added to the readme in addition to the ones already there. Or maybe it even has something in common with issue #20 and should tell the user what to do (hard to foresee all cases though).

I solved it by installing: `sudo apt-get install libc6-dev-i386` on Ubuntu

**Comment by pl-ca** [comment]
This issue should be resolved in version 2.1.0 with commit 24b565684a61590859ca926a98a703b6cec518dc
