### ISSUE TITLE
Your opinion on forks

### ISSUE THREAD

**Issue by niosus** [pl-ca/ClangAutoComplete#25]
Hey @pl-ca. As you have noticed, I am quite inspired by your plugin. There was no plugin before that would be so easy to setup and to hack around. :+1: 

However, I have significantly diverged in my own branch. The changes are at least the following:
- moved from using clang binary to `libclang` 
    + this allows to significantly reduce the setup process for the user
    + also one can autocomplete namespaces and static functions now
    + allows to wrap suggestions in snippet-like syntax to navigate between parameters
    + I am planning to return the clang binary support as an option for user to choose from, but there is a bunch of issues with that currently
- the plugin has turned fully asynchronous
    + on view focus the view is compiled in background
    + when the user types the autocompletions are queried asynchronously and update an already shown autocomplete window on the fly
- changed autocomplete triggers
    + the code will only autocomplete on `.`, `->` or `::`, but not `>` or `:`
    + no autocompletion is triggered for numbers like `42.` (dot in the end) 
- moved most of significant logical parts of code into functions and classes
    + this is about to get even more extreme as I am quite fond of incapsulation. So more refactoring coming as soon as I find time
- Documentation with `Docstring` + all code passes PEP8 linter. (this means no more tabs in code)
- settings changed to expect boolean instead of strings for `true` and `false`

I may have forgotten something, but this amount of changes is already huge. You can see the current state of my branch at https://github.com/niosus/ClangAutoComplete in `master` branch

This leads me to my question. I would gladly do a pull request with all these changes into your branch, but you seem to be quite a busy person and I don't want to be a burden on your shoulders. I understand that it is a huge hassle to check if such an amount of new things work as expected. Also I have no idea how things work on windows... 

So I would rather maintain a fork of your project (probably will make it standalone) and would then give the plugin another name and put it in the Package Manager for Sublime Text. A lot of credit still goes to you, of course, and this is going to be clearly stated.

So my question is. What is your view on this? If you don't mind the fork solution, would you consider updating the licence in your project so that I could conform my work to it?

And thanks again for inspiration and for a really great start for me!

Waiting for your decision! :)

**Comment by pl-ca** [comment]
Hi @niosus, this all sounds great! I have no issue whatsoever with your fork. You are right that I have little interest of spending more time to maintain a bigger plug-in; I only made it to help me in my job, and not replace it :)

Let me know whenever you do a stable release of your plug-in and maybe I'll just switch to yours. Maybe I'll be able to give you a hand for Windows support.

I don't have good knowledge about licensing, do you have any suggestion that I should integrate to clearly allow your project to exist?

**Comment by pl-ca** [comment]
I'll put this one in I believe, should do the trick!

https://www.tldrlegal.com/l/wtfpl

**Comment by niosus** [comment]
Thanks for a fast reply! I am happy that you think in the same way as me. I also like the license you suggested very much! :)

I will let you know upon a stable release, so that you can see if it works nicely for you. Also, yes, help with windows setup would be greatly appreciated.

Thanks again!
I will close this issue then.
