### ISSUE TITLE
A way to find the C/Cpp Standard Header path

### ISSUE THREAD

**Issue by perpetual-motion-man** [pl-ca/ClangAutoComplete#28]
Hi,
Basicly, using `gcc`, we can find the _C Standard Header path_ by command line `$ gcc -E -v hello.c > /dev/null`, notice the `#include <...> search` dirs.

------

A more convenient way is:
for C: `$ echo "" | gcc -v -E -xc -`
for Cpp: `$ echo "" | g++ -v -E -xc++ -`

Hope this will help you!
Regards.

**Comment by pl-ca** [comment]
Very nice! I'll see if I can make use of that to automatically find the standard header files, thanks.

**Comment by pl-ca** [comment]
I have included this feature to be released with version 2.1.0, with commit 24b565684a61590859ca926a98a703b6cec518dc

**Comment by perpetual-motion-man** [comment]
great!
