### ISSUE TITLE
support plugin settings override in project file(*.sublime-project)? 

### ISSUE THREAD

**Issue by canfoderiskii** [pl-ca/ClangAutoComplete#30]
Is it hard to implement?

maybe plugin setting names needs some changing, add a prefix maybe a good choice, for example: "ClangAutoComplete.include_dir"

This feature is useful when my different projects need different include path. It is a horrible experience when i deal with various projects, i have to change the plugin user settings file each time.

Maybe this feature should be implemented globally by sublime itself, but there is a quick workaround for this now. Seems the name changing of plugin settings works, i saw some other plugin did this kind of work

**Comment by pl-ca** [comment]
If you are using projects in sublime, you can copy your settings file in your project base folder as a file named ".clangautocomplete", and it should load that file instead of the general config file.

Have you tried that?

**Comment by canfoderiskii** [comment]
@pl-ca i tried, it works. the path inside include_dir is relative to .clangautocomplete file, am i right?

I was just wondering if there is a way for project-dependent plugin settings at global level, thus every plugin can has its settings being project dependent, so i asked the question.

thanks for your reply.

**Comment by pl-ca** [comment]
>the path inside include_dir is relative to .clangautocomplete file, am i right?

No I think they are relative to a temporary location that is not very useable. If you want relative to the project base directory, I recommend using the following format `"$project_base_path/src"`. The variable `$project_base_path` will expand into the base directory of project.

>I was just wondering if there is a way for project-dependent plugin settings at global level, thus every plugin can has its settings being project dependent, so i asked the question.

I'm not sure, it may be possible. If I can find some time I will have a look.

**Comment by canfoderiskii** [comment]
@pl-ca I placed the .clangautocomplete in the base folder of project and used relative path such as "./src" inside that setting file. It works!
