### ISSUE TITLE
include_file_parent_folder doesn't do what it says

### ISSUE THREAD

**Issue by samirault** [pl-ca/ClangAutoComplete#36]
Setting include_file_parent_folder to "true" includes the parent folder of the parent folder of the current file instead of the parent folder of the current file.

If the file is  "/blah/foo/file.cpp"  the path that ends up being used is "/blah/foo/..".
However the path that should be used is "/blah/foo".

**Comment by pl-ca** [comment]
I understand what you mean. I don't know exactly under what circumstances this option was added but I have to assume that some people are using its current functionality. I would offer adding another separate option like `include_current_folder` to do what you desire and keep the `include_file_parent_folder` as it is.

**Comment by samirault** [comment]
Agreed.  That would be fine with me.

**Comment by pl-ca** [comment]
I added a new option named `include_file_current_folder` and will publish an update to package control with it. I quickly tested and it seemed to work for me. Let me know if you have any trouble.

commit 81278d603d60997036551784847f2579262b2b55
