### ISSUE TITLE
posix paths in include_dirs are not converted correctly to windows paths

### ISSUE THREAD

**Issue by JohannesMP** [pl-ca/ClangAutoComplete#5]
Currently your plugin does not correctly convert the posix-style paths in the settings file to windows-style paths when run in sublime text for windows.

For example, when opening a folder in Sublime that is located at:

    C:\Users\Johannes\Desktop\temp sublime

And the `include_dirs` setting is set as:

    "include_dirs" : [
      "$project_base_path/src"
    ]

If you add `print(repr(dir))` just after <a href=https://github.com/pl-ca/ClangAutoComplete/blob/master/ClangAutoComplete.py#L84>line 84</a> you can see that the directory passed to clang is:

    'C:\\Users\\Johannes\\Desktop\temp sublime/src'

While it should actually be:

    '"C:\\Users\\Johannes\\Desktop\\temp sublime\\src"'

The problems here are:

1. The path following the `$project_base_path` variable is still in posix format
2. The `\\t` is somehow replaced as `\t`
3. The path is not passed in quotes, which (I think) might break the clang commandline later.

------

I hacked together a quick and dirty fix, just so I could use it on my own projects:

		for i in range(0, len(self.include_dirs)):
			self.include_dirs[i] = re.sub("(\$project_base_path)", project_path, self.include_dirs[i])
			self.include_dirs[i] = re.sub("(\$project_name)", project_name, self.include_dirs[i])
			if os.name == "nt":
				self.include_dirs[i] = re.sub("(/)", "\\\\", self.include_dirs[i]);
				self.include_dirs[i] = re.sub("(\\t)", "\\\\t", self.include_dirs[i])
				if "\"" not in self.include_dirs[i]:
					self.include_dirs[i] = "\"" + self.include_dirs[i] + "\"";

But I have basically no experience with python so there is probably a far more elegant way to have `os.path` handle this.

**Comment by pl-ca** [comment]
I will try to replicate this on my Windows PC when I get a chance, I did not thoroughly test Windows so may be there is some issue in the plugin.

However, my first guess is that the format you are using for include_directories is not accepted on Windows.
Can you try to change lines to something similar to the example you see commented below for "clang_binary".
And remove all you don't need (I guess "/usr/include" doesn't make sense on Windows).

e.g.:  

	"$project_base_path\\src", 
or 
	"C:\\workspace\\$project_name", 
etc.

**Comment by JohannesMP** [comment]
One more related thing I noticed: When opening a folder in sublime text the `$project_base_path` variable correctly resolves to the absolute path, which works with my 'fix'. However when opening the same folder through a project, the `$project_base_path` variable resolves to the local posix-style path which seems to break in windows

----

For example, my `include_dirs` is currently set to:

    "include_dirs" : [
        "$project_base_path",
        "$project_base_path/code",
        "$project_base_path/src"
    ],

When I open my project's folder manually (`File->Open Folder...`) the `dir` values appended onto `clang_includes` are in absolute form (including my fix):

    '"C:\\Users\\Johannes\\Desktop\\temp sublime"'
    '"C:\\Users\\Johannes\\Desktop\\temp sublime\\code"'
    '"C:\\Users\\Johannes\\Desktop\\temp sublime\\src"'

Which works fine:
<a href=http://i.imgur.com/MBc8lLn.png><img src=http://i.imgur.com/MBc8lLnl.png /></a>

When I open my project through it's sublime-project file the `dir` values appended onto `clang_includes` are in relative form (including my fix):

    '"."'
    '".\\code"'
    '".\\src"'

Which seems to not work, at least under windows:
<a href=http://i.imgur.com/nX7qeh7.png ><img src=http://i.imgur.com/nX7qeh7l.png /></a>

I'm not sure, but either the formatting needs to be slightly modified for windows to work for relative paths, or it needs to be converted to an absolute path. For now I'll just be using the folder method.

**Comment by JohannesMP** [comment]
Also I noticed that basically all escape characters, not just `/t` are causing issues. For example folders beginning with a,b,n, etc would result in escape characters \a, \b, \n, etc.

The issue seems to be introduced in the re.sub calls that insert the `$project_base_path` and `$project_name` variables. I tried banging my head against it for a bit, and ended up just switching it to a standard string replace:

		for i in range(0, len(self.include_dirs)):
			self.include_dirs[i] = self.include_dirs[i].replace("$project_base_path", project_path)
			self.include_dirs[i] = self.include_dirs[i].replace("$project_name", project_name)
			if os.name == "nt":
				self.include_dirs[i] = re.sub("(/)", "\\\\", self.include_dirs[i])
				if "\"" not in self.include_dirs[i]:
					self.include_dirs[i] = "\"" + self.include_dirs[i] + "\"";

This seems to have fixed all folders for me on windows, although I don't know if this might cause other issues on Mac/Linux

**Comment by pl-ca** [comment]
Thanks for the fix, I am no python expert myself and this looks like it resolves the issue nicely!
Assuming that no other problem remains related to that issue I am closing it.
