### ISSUE TITLE
Please Add CAC to Package Control

### ISSUE THREAD

**Issue by JohannesMP** [pl-ca/ClangAutoComplete#7]
I would really appreciate it if ClangAutoComplete was made available on the Sublime Text Package Control repository (https://packagecontrol.io).

I use Sublime Text on multiple machines and synchronize them by storing my `Packages/User` folder on Dropbox and symlinking it to its proper location. This synchronizes only my settings and Package Control handles downloading the required packages on each of my machines.

However currently, because it lives outside of the `User` folder, I have to install ClangAutoComplete manually on each machine. It would be very convenient if I did not have to do that.

I've recommended ClangAutoComplete to several developers that also use Sublime and I feel that they would be far more likely to give it a try if it was accessible via package control.

While there are several Clang auto completion alternatives already on Package Control, none of them seem to be as simple or cross-platform compatible as your implementation.

**Comment by pl-ca** [comment]
I understand how it would be more convenient. I will take a look at the procedure to do this.

**Comment by pl-ca** [comment]
I have submitted the pull request to packagecontrol, we have to wait for their response now.

**Comment by pl-ca** [comment]
It is now part of packagecontrol. I quickly tested the installation process on Windows and it seems fine. 
Ideally I would like to display the readme file to the user after install, as other plugins are doing, but i'll see how to do that later on. For now, I consider this issue fixed, you can find the plugin over there:

https://packagecontrol.io/packages/ClangAutoComplete
