### ISSUE TITLE
bug in line 79 of file ClangAutoComplete.py

### ISSUE THREAD

**Issue by LxMit** [pl-ca/ClangAutoComplete#8]
**when edit a untitled file without save, the complete does not work and throw out error.**
beacause the ```view.file_name()``` returns ```None``` , so the ```re.findall()``` throw out error.

please fix it , thank you.

**Comment by pl-ca** [comment]
Thanks for raising this issue, I have fixed it in latest version. Editing an unsaved, untitled file will now trigger the suggestions.
