### ISSUE TITLE
No module named "package_control"

### ISSUE THREAD

**Issue by cidadao** [pl-ca/ClangAutoComplete#9]
Hi,

I've just installed ClangAutoComplete throught Package Manager but the plugin won't run. I get this error:
<code>
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\mribeiro\AppData\Roaming\Sublime Text 3\Packages\ClangAutoComplete\package_control.py", line 8, in plugin_loaded
    from package_control import events
ImportError: No module named 'package_control'
</code>

Any idea?

**Comment by pl-ca** [comment]
This file "package_control.py" is not required anyway.
I'm not sure why this is causing you trouble, but I removed it from the repository with new version 1.0.6 (efe69a0). 

Package control should update within an hour and please tell me if it has resolved the problem or not.

**Comment by pl-ca** [comment]
I'll assume this issue is fixed, until I hear otherwise.
